version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=abosad_db
            - DB_USERNAME=abosad
            - DB_PASSWORD=asdasd

    db:
        image: mysql:8.0
        container_name: mysql_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: abosad_db
            MYSQL_USER: abosad
            MYSQL_PASSWORD: asdasd
            MYSQL_ROOT_PASSWORD: asdasd
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    dbdata:
